import "../../declare";
import "../shared/styles/globals.css";
import type { Metadata } from "next";
import { MasterProvider } from "@/shared/ui";
import { Header } from "@/features/ui/header/ui/Header";
import { sfetch } from "@/shared/lib/fetch";
import { contracts } from "@/backend";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // auth hydration
  let auth: contracts.auth.GetResponse | null = null;

  try {
    auth = (
      await (await sfetch("/api/auth", { next: { tags: ["me"] } })).json()
    ).data;
  } catch {
    /** */
  }

  // jsx
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="flex w-screen min-h-screen overflow-x-hidden">
        <MasterProvider auth={auth}>
          <Header auth={auth} />

          {children}
        </MasterProvider>
      </body>
    </html>
  );
}
