import type { Metadata } from "next";
import "../shared/styles/globals.css";
import { MasterProvider } from "@/shared/ui";
import { Header } from "@/features/ui/header/ui/Header";
import { sfetch } from "@/shared/lib/fetch";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // auth hydration
  const auth = await (await sfetch("/api/auth")).json();
  console.log(auth);

  // jsx
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="flex w-screen min-h-screen overflow-x-hidden">
        <MasterProvider>
          <Header />

          {children}
        </MasterProvider>
      </body>
    </html>
  );
}
