import type { Metadata } from "next";
import "../shared/styles/globals.css";
import { MasterProvider } from "@/shared/ui";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <MasterProvider>{children}</MasterProvider>
      </body>
    </html>
  );
}
